# This is a basic workflow to help you get started with Actions

name: Dockerize Next.js web application

# Controls when the action will run. 
on: push
jobs:
  # This workflow contains a single job called "build"
  build-container:
    name: Build Docker Container Image
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code  
        uses: actions/checkout@v2
      - name: Publish to GitHub Packages
        uses: docker/build-push-action@v1 
        with: 
          username: ${{ github.actor }}
          password: $ {{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com 
          repository: ${{ github.repository }}/next 
          tags: latest, ${{ github.run_number }}
      - name: Publish to Docker Hub 
        uses: docker/build-push-action@v1 
        with: 
          username: ${{ github.actor }}
          password: $ {{ secrets.GITHUB_TOKEN }}
          repository: ramona84/next
          tags: latest, ${{ github.run_number }} 

    
